# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e27c1f243cbd4eafd807e4463f493484fc96416b503db6ab71806ccf86dad3df7321df2e5477f17d6e2d0747d26fed70847bf54789817a13cea64f31a071583d

test:
  secret_key_base: c3a9fe0ca89c9686807a873bb6c4da03b0a3f160b991239b88c81a00b99c26fe833a29d094f29a35ded5b8a5cc9aa4f1264e1541ee5542c1bb2ff76984d047b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
